const contacts = [
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'John',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
  {'firstName': 'Alex',
    'lastName': 'Smith',
    'country': 'Mexico',
    'address': '1327 Dear Park Lane',
    'city': 'Baja',
    'state': 'CDMX',
    'zip': '60162',
    'phone': '999-999-9999'
  },
  {'firstName': 'Susan',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Timmy',
    'lastName': 'Anthony',
    'country': 'England',
    'address': '1327 Dear Park Lane',
    'city': 'Mayfair',
    'state': 'London',
    'zip': 'W1J7NW',
    'phone': '999-999-9999'
  },
  {'firstName': 'Jane',
    'lastName': 'Smith',
    'country': 'USA',
    'address': '1327 Dear Park Lane',
    'city': 'Westminster',
    'state': 'MD',
    'zip': '21157',
    'phone': '999-999-9999'
  },
];

export default contacts;
